[package]
name = "hdbconnect"
version = "0.4.10"
authors = ["emabee <meinolf.block@sap.com>"]
description = "A pure rust driver for SAP HANA(TM)"
documentation = "https://docs.rs/hdbconnect/"
keywords = ["relational", "database", "driver", "in-memory", "serde"]
license = "Apache-2.0"
repository = "https://github.com/emabee/rust-hdbconnect"

# This points to a file in the repository (relative to this `Cargo.toml`). The
# contents of this file are stored and indexed in the registry.
#readme = "..."

[dependencies]
byteorder = "1.1"
chrono = { version = "0.4", features = ["serde"] }
#dist_tx = {path = "../dist_tx"}
dist_tx = "0.2"
hex = "0.2"
log = "0.4"
num = "^0.1.40"
r2d2 = "0.7"
rand = "0.3"
rust-crypto = "0.2"
rust_decimal = { version = "0.7", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_db = "0.4"
#serde_db = { path = "../serde_db" }
serde_json = "1.0"
username = "^0.2"
vec_map = "0.8"

[dev-dependencies]
serde_bytes = "0.10"
flexi_logger = "0.8"
# flexi_logger = {path = "../flexi_logger"}
sha2 = "0.6"
