[package]
name = "hdbconnect"
version = "0.0.5"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
byteorder = "*"
flexi_logger = "0.3"
log = "*"
num = "*"
rand = "0.3.9"
rust-crypto = "0.2"
serde = "*"
serde_macros = "*"
time = "*"
vec_map = "*"
