[package]
name = "hdbconnect"
version = "0.2.1"
authors = ["emabee <meinolf.block@sap.com>"]
description = "An experimental pure rust driver for SAP HANA(TM)"
documentation = "https://docs.rs/hdbconnect/"
keywords = ["relational", "database", "driver", "in-memory", "serde"]
license = "Apache-2.0"

#repository = "..."

# This points to a file in the repository (relative to this `Cargo.toml`). The
# contents of this file are stored and indexed in the registry.
#readme = "..."

[dependencies]
byteorder = "1.1"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.2"
log = "0.3"
r2d2 = "0.7"
rand = "0.3"
rust-crypto = "0.2"
serde = "1.0"
serde_bytes = "0.10"
serde_db = "0.3.0"
serde_derive = "1.0"
serde_json = "1.0"
username = "^0.2"
vec_map = "0.8"

[dev-dependencies]
flexi_logger = "0.6"
sha2 = "0.6"
