[package]
name = "hdbconnect"
version = "0.0.25"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
byteorder = "*"
chrono = "*"
flexi_logger = "*"
log = "*"
num = "*"
rand = "*"
rust-crypto = "*"
serde = "*"
serde_derive ="*"
vec_map = "*"
user = "*"

#[dependencies.flexi_logger]
#path = "/dev/rust/projects/flexi_logger"
