[package]
name = "hdbconnect"
version = "0.0.7"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
byteorder = "*"
chrono = "0.2"
flexi_logger = "0.3"
log = "*"
num = "*"
rand = "0.3.9"
rust-crypto = "0.2"
serde = "*"
serde_macros = "*"
vec_map = "*"
