[package]
name = "hdbconnect"
version = "0.0.19"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
byteorder = "0.4"
chrono = "0.2"
flexi_logger = "0.3"
log = "0.3"
num = "0.1"
rand = "0.3"
rust-crypto = "0.2"
serde = "0.6"
serde_macros = "0.6"
vec_map = "0.4"
user = "0.1"
