[package]
name = "hdbconnect"
version = "0.0.29"
authors = ["emabee <meinolf.block@sap.com>"]
description = "An experimental pure rust driver for SAP HANA(TM)"
documentation = "https://docs.rs/hdbconnect/"
keywords = ["relational", "database", "driver", "in-memory", "serde"]
license = "Apache-2.0"

#repository = "..."

# This points to a file in the repository (relative to this `Cargo.toml`). The
# contents of this file are stored and indexed in the registry.
#readme = "..."

[dependencies]
byteorder = "1.0.*"
chrono = { version = "0.3.*", features = ["serde"] }
flexi_logger = "0.5.*"
log = "0.3.*"
rand = "0.3.*"
rust-crypto = "0.2.*"
serde = "0.9.*"
serde_derive ="0.9.*"
serde_json ="0.9.*"
user = "0.1.*"
vec_map = "0.6.*"
