[package]
name = "hdbconnect"
version = "0.0.26"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
byteorder = "*"
chrono = { version = "0.2"}
log = "*"
rand = "*"
rust-crypto = "*"
serde = "*"
user = "*"
vec_map = "*"
