[package]
name = "hdbconnect"
version = "0.11.0"
authors = ["emabee <meinolf.block@sap.com>","Pascal Seitz <pascal.seitz@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/emabee/rust-hdbconnect"
documentation = "https://docs.rs/hdbconnect/"

description = "A pure rust driver for SAP HANA(TM)"
keywords = ["relational", "database", "driver", "serde", "HANA"]
categories = ["database"]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
tls = ["rustls","webpki"]
alpha_routing = []

[dependencies]
blake2 = "0.8.0"
sha2 = "0.8.0"
hmac = "0.7.0"
pbkdf2 = {version = "0.3.0", default-features = false}

bigdecimal = {version = "0.0.14", features = ["serde"]}
byteorder = "1.2"
chrono = { version = "0.4", features = ["serde"] }
cesu8 = "1.1"
#dist_tx = {path = "../dist_tx"}
dist_tx = "0.2"
hex = "0.3"
log = "0.4"
num = "0.2"
r2d2 = "0.8"
rand = "0.5"
rustls = {version = "0.14", optional = true}
secstr = "0.3"
serde = "1.0"
serde_derive = "1.0"
# serde_db = { path = "../serde_db" }
serde_db = "0.6"
serde_json = "1.0"
url = "1.7"
username = "0.2"
vec_map = "0.8"
webpki = {version = "0.18", optional = true}

[dev-dependencies]
serde_bytes = "0.10"
# flexi_logger = {path = "../flexi_logger"}
flexi_logger = "0.10"
version-sync = "0.6"

