[package]
name = "hdbconnect"
version = "0.0.1"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
byteorder = "*"
flexi_logger = "0.3"
log = "*"
rustc-serialize = "*"
time = "*"
rust-crypto = "0.2"
rand = "0.3.9"
